# Generated by Django 3.0 on 2021-08-11 13:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platelage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='platelage',
            name='M_Max_N',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, max_length=10), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='platelage',
            name='M_Max_P',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, max_length=10), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='platelage',
            name='M_N',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, max_length=10), blank=True, null=True, size=None), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='platelage',
            name='M_P',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, max_length=10), blank=True, null=True, size=None), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='platelage',
            name='combinaison_arr_N',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, max_length=10), blank=True, null=True, size=None), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='platelage',
            name='combinaison_arr_P',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, max_length=10), blank=True, null=True, size=None), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='platelage',
            name='pm',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, max_length=10), blank=True, null=True, size=None), blank=True, null=True, size=None),
        ),
    ]
