# Generated by Django 3.0 on 2021-08-15 23:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platelage', '0002_auto_20210811_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='platelage',
            name='B_Mc120_LOCALISE_arr',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, max_length=10), blank=True, null=True, size=None), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='platelage',
            name='ELS_LOCALISE_M',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, max_length=10), blank=True, null=True, size=None), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='platelage',
            name='ELU_LOCALISE_M',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, max_length=10), blank=True, null=True, size=None), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='platelage',
            name='G_ET_A_LOCALISE_arr',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, max_length=10), blank=True, null=True, size=None), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='platelage',
            name='Lx',
            field=models.FloatField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='platelage',
            name='Ly',
            field=models.FloatField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='platelage',
            name='Max_ELU_ELS_LOCALISE_arr',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, max_length=10), blank=True, null=True, size=None), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='platelage',
            name='a_lx',
            field=models.FloatField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='platelage',
            name='ro',
            field=models.FloatField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='platelage',
            name='y_lx',
            field=models.FloatField(blank=True, max_length=12, null=True),
        ),
    ]
