# Generated by Django 3.0 on 2021-06-30 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caractéristique_tablier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('L', models.FloatField(default=0.0)),
                ('lr', models.FloatField(default=0.0)),
                ('lc', models.FloatField(default=0.0)),
                ('nv', models.FloatField(default=0.0)),
                ('lv', models.FloatField(default=0.0)),
                ('lv0', models.FloatField(default=0.0)),
                ('Le', models.FloatField(default=0.0)),
                ('classe', models.FloatField(default=0.0)),
                ('Lprime', models.FloatField(default=0.0)),
                ('a1', models.FloatField(default=0.0)),
                ('a2', models.FloatField(default=0.0)),
                ('Al', models.FloatField(default=0.0)),
                ('cbc', models.FloatField(default=0.0)),
                ('cbt', models.FloatField(default=0.0)),
                ('Bc', models.FloatField(default=30.0)),
                ('Bt', models.FloatField(default=16.0)),
                ('Br', models.FloatField(default=10.0)),
                ('QB', models.FloatField(default=0.0)),
                ('qmc120', models.FloatField(default=18.033)),
                ('Qm', models.FloatField(default=0.0)),
                ('G', models.FloatField(default=0.0)),
                ('SigmaB', models.FloatField(default=0.0)),
                ('SigmaM', models.FloatField(default=0.0)),
                ('Gprime', models.FloatField(default=0.0)),
                ('Bcprime', models.FloatField(default=0.0)),
                ('QBprime', models.FloatField(default=0.0)),
                ('QMprime', models.FloatField(default=0.0)),
                ('SigmaBprime', models.FloatField(default=0.0)),
                ('SigmaMprime', models.FloatField(default=0.0)),
                ('cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.Cart')),
            ],
        ),
    ]
