# Generated by Django 3.0 on 2021-07-04 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0016_poutre_pve'),
        ('caractéristiquetablier', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caractéristique_tablier',
            old_name='Le',
            new_name='epdr',
        ),
        migrations.AddField(
            model_name='caractéristique_tablier',
            name='tablier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='structure.tablier'),
        ),
    ]
