# Generated by Django 3.0 on 2021-07-04 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caractéristiquetablier', '0002_auto_20210704_0121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caractéristique_tablier',
            name='tablier',
        ),
    ]
