# Generated by Django 3.0 on 2021-07-04 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0016_poutre_pve'),
        ('caractéristiquetablier', '0003_remove_caractéristique_tablier_tablier'),
    ]

    operations = [
        migrations.AddField(
            model_name='caractéristique_tablier',
            name='tab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='structure.tablier'),
        ),
    ]
