# Generated by Django 3.0 on 2021-07-05 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caractéristiquetablier', '0005_auto_20210705_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caractéristique_tablier',
            name='Bc_sur_L',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='caractéristique_tablier',
            name='Bc_sur_L_prime',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='caractéristique_tablier',
            name='Br_sur_L_prime',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='caractéristique_tablier',
            name='Bt_sur_L',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='caractéristique_tablier',
            name='Bt_sur_L_prime',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='caractéristique_tablier',
            name='Qm_sur_L',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='caractéristique_tablier',
            name='Qm_sur_L_prime',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='caractéristique_tablier',
            name='qmc120_sur_L',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='caractéristique_tablier',
            name='qmc120_sur_L_prime',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='caractéristique_tablier',
            name='qmc80_sur_L',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='caractéristique_tablier',
            name='qmc80_sur_L_prime',
            field=models.FloatField(default=0.0),
        ),
    ]
