# Generated by Django 3.0 on 2021-07-05 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caractéristiquetablier', '0006_auto_20210705_1326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caractéristique_tablier',
            old_name='Bc_sur_L',
            new_name='Bc',
        ),
        migrations.RenameField(
            model_name='caractéristique_tablier',
            old_name='Bt_sur_L',
            new_name='Br',
        ),
        migrations.RenameField(
            model_name='caractéristique_tablier',
            old_name='QB_sur_L',
            new_name='Bt',
        ),
        migrations.RenameField(
            model_name='caractéristique_tablier',
            old_name='SigmaB',
            new_name='G',
        ),
        migrations.RenameField(
            model_name='caractéristique_tablier',
            old_name='SigmaB_sur_L_prime',
            new_name='L',
        ),
        migrations.RenameField(
            model_name='caractéristique_tablier',
            old_name='SigmaM',
            new_name='Lc',
        ),
        migrations.RenameField(
            model_name='caractéristique_tablier',
            old_name='SigmaM_sur_L_prime',
            new_name='Lr',
        ),
        migrations.RemoveField(
            model_name='caractéristique_tablier',
            name='Br_sur_L',
        ),
        migrations.AddField(
            model_name='caractéristique_tablier',
            name='QA',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='caractéristique_tablier',
            name='QB',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='caractéristique_tablier',
            name='cdmdB',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='caractéristique_tablier',
            name='cdmdBprime',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='caractéristique_tablier',
            name='cdmdM',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='caractéristique_tablier',
            name='cdmdMprime',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='caractéristique_tablier',
            name='epdr',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='caractéristique_tablier',
            name='nBc',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='caractéristique_tablier',
            name='nBc_sur_L_prime',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='caractéristique_tablier',
            name='nBt',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='caractéristique_tablier',
            name='nBt_sur_L_prime',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='caractéristique_tablier',
            name='pte',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='caractéristique_tablier',
            name='ptp',
            field=models.FloatField(default=0.0),
        ),
    ]
