# Generated by Django 3.0 on 2021-07-24 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repartitiontransversale', '0002_auto_20210724_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='repartition_transversale',
            name='ro_e',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
