# Generated by Django 3.0 on 2021-07-29 19:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repartitiontransversale', '0004_auto_20210728_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='repartition_transversale',
            name='p1_A_1V',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, max_length=10), blank=True, null=True, size=None), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='repartition_transversale',
            name='p1_Bc_1V',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, max_length=10), blank=True, null=True, size=None), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='repartition_transversale',
            name='p1_Bc_2V',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, max_length=10), blank=True, null=True, size=None), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='repartition_transversale',
            name='p1_Br',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, max_length=10), blank=True, null=True, size=None), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='repartition_transversale',
            name='p1_Bt_1V',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, max_length=10), blank=True, null=True, size=None), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='repartition_transversale',
            name='p1_Bt_2V',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, max_length=10), blank=True, null=True, size=None), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='repartition_transversale',
            name='p1_D240',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, max_length=10), blank=True, null=True, size=None), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='repartition_transversale',
            name='p1_G',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, max_length=10), blank=True, null=True, size=None), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='repartition_transversale',
            name='p1_Mc120',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, max_length=10), blank=True, null=True, size=None), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='repartition_transversale',
            name='p1_qtr_1V',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, max_length=10), blank=True, null=True, size=None), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='repartition_transversale',
            name='p1_qtr_2V',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, max_length=10), blank=True, null=True, size=None), blank=True, null=True, size=None),
        ),
    ]
