# Generated by Django 3.0 on 2021-07-30 11:23

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repartitiontransversale', '0006_repartition_transversale_p1_a_2v'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repartition_transversale',
            name='p1_A_1V',
        ),
        migrations.RemoveField(
            model_name='repartition_transversale',
            name='p1_A_2V',
        ),
        migrations.RemoveField(
            model_name='repartition_transversale',
            name='p1_Bc_1V',
        ),
        migrations.RemoveField(
            model_name='repartition_transversale',
            name='p1_Bc_2V',
        ),
        migrations.RemoveField(
            model_name='repartition_transversale',
            name='p1_Br',
        ),
        migrations.RemoveField(
            model_name='repartition_transversale',
            name='p1_Bt_1V',
        ),
        migrations.RemoveField(
            model_name='repartition_transversale',
            name='p1_Bt_2V',
        ),
        migrations.RemoveField(
            model_name='repartition_transversale',
            name='p1_D240',
        ),
        migrations.RemoveField(
            model_name='repartition_transversale',
            name='p1_G',
        ),
        migrations.RemoveField(
            model_name='repartition_transversale',
            name='p1_Mc120',
        ),
        migrations.RemoveField(
            model_name='repartition_transversale',
            name='p1_qtr_1V',
        ),
        migrations.RemoveField(
            model_name='repartition_transversale',
            name='p1_qtr_2V',
        ),
        migrations.AddField(
            model_name='repartition_transversale',
            name='poutre_1',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='repartition_transversale',
            name='poutre_2',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='repartition_transversale',
            name='poutre_3',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
