# Generated by Django 3.0 on 2021-07-18 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geometry', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section_type_01',
            old_name='IG',
            new_name='IG_avec_hourdis',
        ),
        migrations.RenameField(
            model_name='section_type_01',
            old_name='V',
            new_name='IG_sans_hourdis',
        ),
        migrations.RenameField(
            model_name='section_type_01',
            old_name='V_prime',
            new_name='V_avec_hourdis',
        ),
        migrations.RenameField(
            model_name='section_type_01',
            old_name='rendement',
            new_name='V_prime_avec_hourdis',
        ),
        migrations.RenameField(
            model_name='section_type_02',
            old_name='IG',
            new_name='IG_avec_hourdis',
        ),
        migrations.RenameField(
            model_name='section_type_02',
            old_name='V',
            new_name='IG_sans_hourdis',
        ),
        migrations.RenameField(
            model_name='section_type_02',
            old_name='V_prime',
            new_name='V_avec_hourdis',
        ),
        migrations.RenameField(
            model_name='section_type_02',
            old_name='rendement',
            new_name='V_prime_avec_hourdis',
        ),
        migrations.AddField(
            model_name='section_type_01',
            name='V_prime_sans_hourdis',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='section_type_01',
            name='V_sans_hourdis',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='section_type_01',
            name='rendement_avec_hourdis',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='section_type_01',
            name='rendement_sans_hourdis',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='section_type_02',
            name='V_prime_sans_hourdis',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='section_type_02',
            name='V_sans_hourdis',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='section_type_02',
            name='rendement_avec_hourdis',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='section_type_02',
            name='rendement_sans_hourdis',
            field=models.FloatField(default=0.0),
        ),
    ]
