# Generated by Django 3.0 on 2021-07-18 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geometry', '0003_auto_20210718_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionadded',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
