# Generated by Django 3.0 on 2021-06-30 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0003_corniche_s_corniche'),
    ]

    operations = [
        migrations.RenameField(
            model_name='corniche',
            old_name='P_cornche',
            new_name='P_corniche',
        ),
    ]
