# Generated by Django 3.0 on 2021-07-01 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('structure', '0005_trottoir'),
    ]

    operations = [
        migrations.CreateModel(
            name='glissiere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('Pvg', models.FloatField(blank=True, default=0.0, null=True)),
                ('L_glissiere', models.FloatField(default=0.0)),
                ('P_glissiere', models.FloatField(default=0.0)),
                ('cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.Cart')),
            ],
        ),
        migrations.CreateModel(
            name='garde_corps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('Pvgc', models.FloatField(blank=True, default=0.0, null=True)),
                ('L_garde_corps', models.FloatField(default=0.0)),
                ('P_garde_corps', models.FloatField(default=0.0)),
                ('cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.Cart')),
            ],
        ),
    ]
