# Generated by Django 3.0 on 2021-07-02 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0006_garde_corps_glissiere'),
    ]

    operations = [
        migrations.AddField(
            model_name='poutre',
            name='L_poutre',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='poutre',
            name='L_total_sections',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
