# Generated by Django 3.0 on 2021-07-02 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0007_auto_20210702_0117'),
    ]

    operations = [
        migrations.AddField(
            model_name='poutre',
            name='P_pre_dale',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='poutre',
            name='S_pre_dalle',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='poutre',
            name='S_total_pre_dalle',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='poutre',
            name='V_total_pre_dalle',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='poutre',
            name='b_pre_dalle',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='poutre',
            name='h_pre_dalle',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
