# Generated by Django 3.0 on 2021-07-02 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0008_auto_20210702_0120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poutre',
            old_name='P_pre_dale',
            new_name='P_pre_dalle',
        ),
    ]
