# Generated by Django 3.0 on 2021-07-02 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('structure', '0009_auto_20210702_0123'),
    ]

    operations = [
        migrations.CreateModel(
            name='dalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('pvd', models.FloatField(default=0.0)),
                ('b_dalle', models.FloatField(default=0.0)),
                ('L_dalle', models.FloatField(blank=True, default=0.0, null=True)),
                ('h_dalle', models.FloatField(default=0.0)),
                ('S_dalle', models.FloatField(blank=True, default=0.0, null=True)),
                ('V_dalle', models.FloatField(blank=True, default=0.0, null=True)),
                ('P_dalle', models.FloatField(blank=True, default=0.0, null=True)),
                ('cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.Cart')),
            ],
        ),
    ]
