# Generated by Django 3.0 on 2021-07-02 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0010_dalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='dalle',
            name='P_revetement',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='dalle',
            name='S_revetement',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='dalle',
            name='V_revetement',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='dalle',
            name='h_revetement',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='dalle',
            name='pvr',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
