# Generated by Django 3.0 on 2021-07-02 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0011_auto_20210702_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dalle',
            name='P_revetement',
        ),
        migrations.RemoveField(
            model_name='dalle',
            name='S_revetement',
        ),
        migrations.RemoveField(
            model_name='dalle',
            name='V_revetement',
        ),
        migrations.RemoveField(
            model_name='dalle',
            name='h_revetement',
        ),
        migrations.RemoveField(
            model_name='dalle',
            name='pvr',
        ),
    ]
