# Generated by Django 3.0 on 2021-07-02 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('structure', '0012_auto_20210702_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='tablier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('Lr', models.FloatField(blank=True, default=0.0, null=True)),
                ('Lc', models.FloatField(default=0.0)),
                ('pvr', models.FloatField(default=0.0)),
                ('h_revetement', models.FloatField(default=0.0)),
                ('cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.Cart')),
                ('corniche_droite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='corniche_droite', to='structure.corniche')),
                ('corniche_gauche', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='corniche_gauche', to='structure.corniche')),
                ('dalle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='structure.dalle')),
                ('garde_corps_droite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='garde_corps_droite', to='structure.garde_corps')),
                ('garde_corps_gauche', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='garde_corps_gauche', to='structure.garde_corps')),
                ('glissiere_droite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='glissiere_droite', to='structure.glissiere')),
                ('glissiere_gauche', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='glissiere_gauche', to='structure.glissiere')),
                ('poutre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='structure.poutre')),
                ('trottoir_droite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trottoir_droite', to='structure.trottoir')),
                ('trottoir_gauche', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trottoir_gauche', to='structure.trottoir')),
            ],
        ),
    ]
