# Generated by Django 3.0 on 2021-07-19 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0016_poutre_pve'),
    ]

    operations = [
        migrations.AddField(
            model_name='trottoir',
            name='largeur_trottoir',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
