# Generated by Django 3.0 on 2021-07-07 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('répartitionlongitudinal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='cart',
        ),
        migrations.DeleteModel(
            name='repartition_longitudinal',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
