# Generated by Django 3.0 on 2021-07-08 08:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('répartitionlongitudinal', '0004_auto_20210707_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='repartition_longitudinal',
            name='Bc_TOTAL',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), blank=True, null=True, size=None), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='repartition_longitudinal',
            name='Br_TOTAL',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), blank=True, null=True, size=None), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='repartition_longitudinal',
            name='Bt_TOTAL',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), blank=True, null=True, size=None), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='repartition_longitudinal',
            name='D240_TOTAL',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), blank=True, null=True, size=None), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='repartition_longitudinal',
            name='M_Bc_barre',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), blank=True, null=True, size=None), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='repartition_longitudinal',
            name='M_Bt_barre',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), blank=True, null=True, size=None), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='repartition_longitudinal',
            name='M_Mc120_TOTAL',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), blank=True, null=True, size=None), blank=True, null=True, size=None),
        ),
    ]
