# Generated by Django 3.0 on 2021-07-08 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('répartitionlongitudinal', '0005_auto_20210708_0930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repartition_longitudinal',
            old_name='M_Mc120_TOTAL',
            new_name='Mc120_TOTAL',
        ),
    ]
