# Generated by Django 3.0 on 2021-07-08 12:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('répartitionlongitudinal', '0006_auto_20210708_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repartition_longitudinal',
            name='A_TOTAL',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, max_length=10), blank=True, null=True, size=None), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='repartition_longitudinal',
            name='Bc_TOTAL',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, max_length=10), blank=True, null=True, size=None), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='repartition_longitudinal',
            name='Br_TOTAL',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, max_length=10), blank=True, null=True, size=None), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='repartition_longitudinal',
            name='Bt_TOTAL',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, max_length=10), blank=True, null=True, size=None), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='repartition_longitudinal',
            name='D240_TOTAL',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, max_length=10), blank=True, null=True, size=None), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='repartition_longitudinal',
            name='G',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, max_length=10), blank=True, null=True, size=None), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='repartition_longitudinal',
            name='M_Bc_barre',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, max_length=10), blank=True, null=True, size=None), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='repartition_longitudinal',
            name='M_Bt_barre',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, max_length=10), blank=True, null=True, size=None), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='repartition_longitudinal',
            name='Mc120_TOTAL',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, max_length=10), blank=True, null=True, size=None), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='repartition_longitudinal',
            name='qtr_TOTAL',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, max_length=10), blank=True, null=True, size=None), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='repartition_longitudinal',
            name='title',
            field=models.FloatField(max_length=120),
        ),
    ]
