# Generated by Django 3.0 on 2021-07-08 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('répartitionlongitudinal', '0007_auto_20210708_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repartition_longitudinal',
            name='title',
            field=models.CharField(max_length=120),
        ),
    ]
