# Generated by Django 3.0 on 2021-07-08 13:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('répartitionlongitudinal', '0010_auto_20210708_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repartition_longitudinal',
            name='qtr_TOTAL',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, max_length=10), blank=True, null=True, size=None), blank=True, null=True, size=None), blank=True, null=True, size=None),
        ),
    ]
