# Generated by Django 3.0 on 2021-07-08 13:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('répartitionlongitudinal', '0012_auto_20210708_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repartition_longitudinal',
            name='M_Bc_barre',
        ),
        migrations.AddField(
            model_name='repartition_longitudinal',
            name='M_BC_TOTAL',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, max_length=10), blank=True, null=True, size=None), blank=True, null=True, size=None), blank=True, null=True, size=None),
        ),
    ]
