# Generated by Django 3.0 on 2021-07-08 14:17

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('répartitionlongitudinal', '0013_auto_20210708_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repartition_longitudinal',
            name='M_BC_TOTAL',
        ),
        migrations.AddField(
            model_name='repartition_longitudinal',
            name='BC_BARRE_TOTAL',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
