# Generated by Django 3.0 on 2021-07-08 17:12

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('répartitionlongitudinal', '0014_auto_20210708_1517'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repartition_longitudinal',
            old_name='BC_BARRE_TOTAL',
            new_name='P3_Critique',
        ),
        migrations.AddField(
            model_name='repartition_longitudinal',
            name='P4_Critique',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
