# Generated by Django 3.0 on 2021-07-10 13:20

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('répartitionlongitudinal', '0015_auto_20210708_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='repartition_longitudinal',
            name='P1_BT',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
