# Generated by Django 3.0 on 2021-07-11 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('répartitionlongitudinal', '0016_repartition_longitudinal_p1_bt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repartition_longitudinal',
            name='M_Bt_barre',
        ),
    ]
