# Generated by Django 3.0 on 2021-07-12 21:36

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('répartitionlongitudinal', '0017_remove_repartition_longitudinal_m_bt_barre'),
    ]

    operations = [
        migrations.AddField(
            model_name='repartition_longitudinal',
            name='detail_M_Bc_Total',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
