# Generated by Django 3.0 on 2021-07-13 14:11

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('répartitionlongitudinal', '0018_repartition_longitudinal_detail_m_bc_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repartition_longitudinal',
            old_name='detail_M_Bc_Total',
            new_name='detail_M_Bc_Total_sense_1',
        ),
        migrations.AddField(
            model_name='repartition_longitudinal',
            name='detail_M_Bc_Total_sense_2',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
