# Generated by Django 3.0 on 2021-07-13 22:04

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('répartitionlongitudinal', '0019_auto_20210713_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='repartition_longitudinal',
            name='detail_T_Bc',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
