# Generated by Django 3.0 on 2021-07-13 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('répartitionlongitudinal', '0020_repartition_longitudinal_detail_t_bc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repartition_longitudinal',
            old_name='detail_T_Bc',
            new_name='T_Bc_detail',
        ),
    ]
