# Generated by Django 3.0 on 2021-07-15 15:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('répartitionlongitudinal', '0021_auto_20210713_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='repartition_longitudinal',
            name='M_Bc_Total_les_2_sense',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, max_length=10, null=True), blank=True, null=True, size=None),
        ),
    ]
