# Generated by Django 3.0 on 2021-07-15 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('répartitionlongitudinal', '0022_repartition_longitudinal_m_bc_total_les_2_sense'),
    ]

    operations = [
        migrations.AddField(
            model_name='repartition_longitudinal',
            name='xcritique',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
