# Generated by Django 3.0 on 2021-07-15 16:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('répartitionlongitudinal', '0023_repartition_longitudinal_xcritique'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repartition_longitudinal',
            old_name='Bc_TOTAL',
            new_name='Bc_TOTAL_N_VOIE',
        ),
        migrations.AddField(
            model_name='repartition_longitudinal',
            name='Bc_TOTAL_UNE_VOIE',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, max_length=10), blank=True, null=True, size=None), blank=True, null=True, size=None),
        ),
    ]
