# Generated by Django 3.0 on 2021-07-15 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('répartitionlongitudinal', '0026_auto_20210715_1951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repartition_longitudinal',
            old_name='M_Bc_TOTAL',
            new_name='Bc_TOTAL',
        ),
    ]
